### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Decapitater** [p4wnsolo/breach-torrents#1]
.

**Comment by p4wnsolo** [comment]
Hello comrade

I'm almost ready to re-join the w0rld

Finally got my visa started

And a place to live 

I'll be back in full force by Feb 1, this time with a house and an office dedicated just to h4xoring

Hope you're doing well!

See you soon

**Comment by Decapitater** [comment]
Good comrade , let's go !

**Comment by Decapitater** [comment]
@p4wnsolo  ? , Meet me in place I have a idea
